#screen var
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "ukraine"
PLAYER_START_X = 100
PLAYER_START_Y = 100
CHARACTER_SCALING = 1

PLAYER_MOVEMENT_SPEED = 4
BULLET_SPEED = 6
SPRITE_SCALING_BULLET = 1